version: '3'

services:
  redis:
    container_name: redis
    image: redis:6.0.7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - ./data/redis:/var/lib/redis
    ports:
      - 6379:6379
    env_file:
      - ../.env  